import DataModel from "../models/DataModel";

export const data: DataModel[] = [
  // Basic Hiragana
  {
    id: 1,
    symbol: "あ",
    romaji: "a",
    category: "hiragana",
    type: "basic",
    column: "a",
  },
  {
    id: 2,
    symbol: "い",
    romaji: "i",
    category: "hiragana",
    type: "basic",
    column: "a",
  },
  {
    id: 3,
    symbol: "う",
    romaji: "u",
    category: "hiragana",
    type: "basic",
    column: "a",
  },
  {
    id: 4,
    symbol: "え",
    romaji: "e",
    category: "hiragana",
    type: "basic",
    column: "a",
  },
  {
    id: 5,
    symbol: "お",
    romaji: "o",
    category: "hiragana",
    type: "basic",
    column: "a",
  },
  {
    id: 6,
    symbol: "か",
    romaji: "ka",
    category: "hiragana",
    type: "basic",
    column: "k",
  },
  {
    id: 7,
    symbol: "き",
    romaji: "ki",
    category: "hiragana",
    type: "basic",
    column: "k",
  },
  {
    id: 8,
    symbol: "く",
    romaji: "ku",
    category: "hiragana",
    type: "basic",
    column: "k",
  },
  {
    id: 9,
    symbol: "け",
    romaji: "ke",
    category: "hiragana",
    type: "basic",
    column: "k",
  },
  {
    id: 10,
    symbol: "こ",
    romaji: "ko",
    category: "hiragana",
    type: "basic",
    column: "k",
  },
  {
    id: 11,
    symbol: "さ",
    romaji: "sa",
    category: "hiragana",
    type: "basic",
    column: "s",
  },
  {
    id: 12,
    symbol: "し",
    romaji: "shi",
    category: "hiragana",
    type: "basic",
    column: "s",
  },
  {
    id: 13,
    symbol: "す",
    romaji: "su",
    category: "hiragana",
    type: "basic",
    column: "s",
  },
  {
    id: 14,
    symbol: "せ",
    romaji: "se",
    category: "hiragana",
    type: "basic",
    column: "s",
  },
  {
    id: 15,
    symbol: "そ",
    romaji: "so",
    category: "hiragana",
    type: "basic",
    column: "s",
  },
  {
    id: 16,
    symbol: "た",
    romaji: "ta",
    category: "hiragana",
    type: "basic",
    column: "t",
  },
  {
    id: 17,
    symbol: "ち",
    romaji: "chi",
    category: "hiragana",
    type: "basic",
    column: "t",
  },
  {
    id: 18,
    symbol: "つ",
    romaji: "tsu",
    category: "hiragana",
    type: "basic",
    column: "t",
  },
  {
    id: 19,
    symbol: "て",
    romaji: "te",
    category: "hiragana",
    type: "basic",
    column: "t",
  },
  {
    id: 20,
    symbol: "と",
    romaji: "to",
    category: "hiragana",
    type: "basic",
    column: "t",
  },
  {
    id: 21,
    symbol: "な",
    romaji: "na",
    category: "hiragana",
    type: "basic",
    column: "n",
  },
  {
    id: 22,
    symbol: "に",
    romaji: "ni",
    category: "hiragana",
    type: "basic",
    column: "n",
  },
  {
    id: 23,
    symbol: "ぬ",
    romaji: "nu",
    category: "hiragana",
    type: "basic",
    column: "n",
  },
  {
    id: 24,
    symbol: "ね",
    romaji: "ne",
    category: "hiragana",
    type: "basic",
    column: "n",
  },
  {
    id: 25,
    symbol: "の",
    romaji: "no",
    category: "hiragana",
    type: "basic",
    column: "n",
  },
  {
    id: 26,
    symbol: "は",
    romaji: "ha",
    category: "hiragana",
    type: "basic",
    column: "h",
  },
  {
    id: 27,
    symbol: "ひ",
    romaji: "hi",
    category: "hiragana",
    type: "basic",
    column: "h",
  },
  {
    id: 28,
    symbol: "ふ",
    romaji: "fu",
    category: "hiragana",
    type: "basic",
    column: "h",
  },
  {
    id: 29,
    symbol: "へ",
    romaji: "he",
    category: "hiragana",
    type: "basic",
    column: "h",
  },
  {
    id: 30,
    symbol: "ほ",
    romaji: "ho",
    category: "hiragana",
    type: "basic",
    column: "h",
  },
  {
    id: 31,
    symbol: "ま",
    romaji: "ma",
    category: "hiragana",
    type: "basic",
    column: "m",
  },
  {
    id: 32,
    symbol: "み",
    romaji: "mi",
    category: "hiragana",
    type: "basic",
    column: "m",
  },
  {
    id: 33,
    symbol: "む",
    romaji: "mu",
    category: "hiragana",
    type: "basic",
    column: "m",
  },
  {
    id: 34,
    symbol: "め",
    romaji: "me",
    category: "hiragana",
    type: "basic",
    column: "m",
  },
  {
    id: 35,
    symbol: "も",
    romaji: "mo",
    category: "hiragana",
    type: "basic",
    column: "m",
  },
  {
    id: 36,
    symbol: "や",
    romaji: "ya",
    category: "hiragana",
    type: "basic",
    column: "y",
  },
  {
    id: 37,
    symbol: "ゆ",
    romaji: "yu",
    category: "hiragana",
    type: "basic",
    column: "y",
  },
  {
    id: 38,
    symbol: "よ",
    romaji: "yo",
    category: "hiragana",
    type: "basic",
    column: "y",
  },
  {
    id: 39,
    symbol: "ら",
    romaji: "ra",
    category: "hiragana",
    type: "basic",
    column: "r",
  },
  {
    id: 40,
    symbol: "り",
    romaji: "ri",
    category: "hiragana",
    type: "basic",
    column: "r",
  },
  {
    id: 41,
    symbol: "る",
    romaji: "ru",
    category: "hiragana",
    type: "basic",
    column: "r",
  },
  {
    id: 42,
    symbol: "れ",
    romaji: "re",
    category: "hiragana",
    type: "basic",
    column: "r",
  },
  {
    id: 43,
    symbol: "ろ",
    romaji: "ro",
    category: "hiragana",
    type: "basic",
    column: "r",
  },
  {
    id: 44,
    symbol: "わ",
    romaji: "wa",
    category: "hiragana",
    type: "basic",
    column: "w",
  },
  {
    id: 45,
    symbol: "を",
    romaji: "wo",
    category: "hiragana",
    type: "basic",
    column: "w",
  },
  {
    id: 46,
    symbol: "ん",
    romaji: "n",
    category: "hiragana",
    type: "basic",
    column: "ん",
  },
  // Diacritic Hiragana
  {
    id: 47,
    symbol: "が",
    romaji: "ga",
    category: "hiragana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 48,
    symbol: "ぎ",
    romaji: "gi",
    category: "hiragana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 49,
    symbol: "ぐ",
    romaji: "gu",
    category: "hiragana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 50,
    symbol: "げ",
    romaji: "ge",
    category: "hiragana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 51,
    symbol: "ご",
    romaji: "go",
    category: "hiragana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 52,
    symbol: "ざ",
    romaji: "za",
    category: "hiragana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 53,
    symbol: "じ",
    romaji: "ji",
    category: "hiragana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 54,
    symbol: "ず",
    romaji: "zu",
    category: "hiragana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 55,
    symbol: "ぜ",
    romaji: "ze",
    category: "hiragana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 56,
    symbol: "ぞ",
    romaji: "zo",
    category: "hiragana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 57,
    symbol: "だ",
    romaji: "da",
    category: "hiragana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 58,
    symbol: "ぢ",
    romaji: "ji",
    category: "hiragana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 59,
    symbol: "づ",
    romaji: "zu",
    category: "hiragana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 60,
    symbol: "で",
    romaji: "de",
    category: "hiragana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 61,
    symbol: "ど",
    romaji: "do",
    category: "hiragana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 62,
    symbol: "ば",
    romaji: "ba",
    category: "hiragana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 63,
    symbol: "び",
    romaji: "bi",
    category: "hiragana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 64,
    symbol: "ぶ",
    romaji: "bu",
    category: "hiragana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 65,
    symbol: "べ",
    romaji: "be",
    category: "hiragana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 66,
    symbol: "ぼ",
    romaji: "bo",
    category: "hiragana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 67,
    symbol: "ぱ",
    romaji: "pa",
    category: "hiragana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 68,
    symbol: "ぴ",
    romaji: "pi",
    category: "hiragana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 69,
    symbol: "ぷ",
    romaji: "pu",
    category: "hiragana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 70,
    symbol: "ぺ",
    romaji: "pe",
    category: "hiragana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 71,
    symbol: "ぽ",
    romaji: "po",
    category: "hiragana",
    type: "diacritic",
    column: "p",
  },
  // Combination Hiragana
  {
    id: 72,
    symbol: "きゃ",
    romaji: "kya",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 73,
    symbol: "きゅ",
    romaji: "kyu",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 74,
    symbol: "きょ",
    romaji: "kyo",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 75,
    symbol: "ぎゃ",
    romaji: "gya",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 76,
    symbol: "ぎゅ",
    romaji: "gyu",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 77,
    symbol: "ぎょ",
    romaji: "gyo",
    category: "hiragana",
    type: "combination",
    column: "ky",
  },
  {
    id: 78,
    symbol: "しゃ",
    romaji: "sha",
    category: "hiragana",
    type: "combination",
    column: "sh",
  },
  {
    id: 79,
    symbol: "しゅ",
    romaji: "shu",
    category: "hiragana",
    type: "combination",
    column: "sh",
  },
  {
    id: 80,
    symbol: "しょ",
    romaji: "sho",
    category: "hiragana",
    type: "combination",
    column: "sh",
  },
  {
    id: 81,
    symbol: "じゃ",
    romaji: "ja",
    category: "hiragana",
    type: "combination",
    column: "sh",
  },
  {
    id: 82,
    symbol: "じゅ",
    romaji: "ju",
    category: "hiragana",
    type: "combination",
    column: "j",
  },
  {
    id: 83,
    symbol: "じょ",
    romaji: "jo",
    category: "hiragana",
    type: "combination",
    column: "j",
  },
  {
    id: 84,
    symbol: "ちゃ",
    romaji: "cha",
    category: "hiragana",
    type: "combination",
    column: "ch",
  },
  {
    id: 85,
    symbol: "ちゅ",
    romaji: "chu",
    category: "hiragana",
    type: "combination",
    column: "ch",
  },
  {
    id: 86,
    symbol: "ちょ",
    romaji: "cho",
    category: "hiragana",
    type: "combination",
    column: "ch",
  },
  {
    id: 87,
    symbol: "にゃ",
    romaji: "nya",
    category: "hiragana",
    type: "combination",
    column: "ny",
  },
  {
    id: 88,
    symbol: "にゅ",
    romaji: "nyu",
    category: "hiragana",
    type: "combination",
    column: "ny",
  },
  {
    id: 89,
    symbol: "にょ",
    romaji: "nyo",
    category: "hiragana",
    type: "combination",
    column: "ny",
  },
  {
    id: 90,
    symbol: "ひゃ",
    romaji: "hya",
    category: "hiragana",
    type: "combination",
    column: "hy",
  },
  {
    id: 91,
    symbol: "ひゅ",
    romaji: "hyu",
    category: "hiragana",
    type: "combination",
    column: "hy",
  },
  {
    id: 92,
    symbol: "ひょ",
    romaji: "hyo",
    category: "hiragana",
    type: "combination",
    column: "hy",
  },
  {
    id: 93,
    symbol: "びゃ",
    romaji: "bya",
    category: "hiragana",
    type: "combination",
    column: "by",
  },
  {
    id: 94,
    symbol: "びゅ",
    romaji: "byu",
    category: "hiragana",
    type: "combination",
    column: "by",
  },
  {
    id: 95,
    symbol: "びょ",
    romaji: "byo",
    category: "hiragana",
    type: "combination",
    column: "by",
  },
  {
    id: 96,
    symbol: "ぴゃ",
    romaji: "pya",
    category: "hiragana",
    type: "combination",
    column: "py",
  },
  {
    id: 97,
    symbol: "ぴゅ",
    romaji: "pyu",
    category: "hiragana",
    type: "combination",
    column: "py",
  },
  {
    id: 98,
    symbol: "ぴょ",
    romaji: "pyo",
    category: "hiragana",
    type: "combination",
    column: "py",
  },
  {
    id: 99,
    symbol: "みゃ",
    romaji: "mya",
    category: "hiragana",
    type: "combination",
    column: "my",
  },
  {
    id: 100,
    symbol: "みゅ",
    romaji: "myu",
    category: "hiragana",
    type: "combination",
    column: "my",
  },
  {
    id: 101,
    symbol: "みょ",
    romaji: "myo",
    category: "hiragana",
    type: "combination",
    column: "my",
  },
  {
    id: 102,
    symbol: "りゃ",
    romaji: "rya",
    category: "hiragana",
    type: "combination",
    column: "ry",
  },
  {
    id: 103,
    symbol: "りゅ",
    romaji: "ryu",
    category: "hiragana",
    type: "combination",
    column: "ry",
  },
  {
    id: 104,
    symbol: "りょ",
    romaji: "ryo",
    category: "hiragana",
    type: "combination",
    column: "ry",
  },

  // Basic Katakana
  {
    id: 1101,
    symbol: "ア",
    romaji: "a",
    category: "katakana",
    type: "basic",
    column: "a",
  },
  {
    id: 1102,
    symbol: "イ",
    romaji: "i",
    category: "katakana",
    type: "basic",
    column: "a",
  },
  {
    id: 1103,
    symbol: "ウ",
    romaji: "u",
    category: "katakana",
    type: "basic",
    column: "a",
  },
  {
    id: 1104,
    symbol: "エ",
    romaji: "e",
    category: "katakana",
    type: "basic",
    column: "a",
  },
  {
    id: 105,
    symbol: "オ",
    romaji: "o",
    category: "katakana",
    type: "basic",
    column: "a",
  },
  {
    id: 106,
    symbol: "カ",
    romaji: "ka",
    category: "katakana",
    type: "basic",
    column: "k",
  },
  {
    id: 107,
    symbol: "キ",
    romaji: "ki",
    category: "katakana",
    type: "basic",
    column: "k",
  },
  {
    id: 108,
    symbol: "ク",
    romaji: "ku",
    category: "katakana",
    type: "basic",
    column: "k",
  },
  {
    id: 109,
    symbol: "ケ",
    romaji: "ke",
    category: "katakana",
    type: "basic",
    column: "k",
  },
  {
    id: 110,
    symbol: "コ",
    romaji: "ko",
    category: "katakana",
    type: "basic",
    column: "k",
  },
  {
    id: 111,
    symbol: "サ",
    romaji: "sa",
    category: "katakana",
    type: "basic",
    column: "s",
  },
  {
    id: 112,
    symbol: "シ",
    romaji: "shi",
    category: "katakana",
    type: "basic",
    column: "s",
  },
  {
    id: 113,
    symbol: "ス",
    romaji: "su",
    category: "katakana",
    type: "basic",
    column: "s",
  },
  {
    id: 114,
    symbol: "セ",
    romaji: "se",
    category: "katakana",
    type: "basic",
    column: "s",
  },
  {
    id: 115,
    symbol: "ソ",
    romaji: "so",
    category: "katakana",
    type: "basic",
    column: "s",
  },
  {
    id: 116,
    symbol: "タ",
    romaji: "ta",
    category: "katakana",
    type: "basic",
    column: "t",
  },
  {
    id: 117,
    symbol: "チ",
    romaji: "chi",
    category: "katakana",
    type: "basic",
    column: "t",
  },
  {
    id: 118,
    symbol: "ツ",
    romaji: "tsu",
    category: "katakana",
    type: "basic",
    column: "t",
  },
  {
    id: 119,
    symbol: "テ",
    romaji: "te",
    category: "katakana",
    type: "basic",
    column: "t",
  },
  {
    id: 120,
    symbol: "ト",
    romaji: "to",
    category: "katakana",
    type: "basic",
    column: "t",
  },
  {
    id: 121,
    symbol: "ナ",
    romaji: "na",
    category: "katakana",
    type: "basic",
    column: "n",
  },
  {
    id: 122,
    symbol: "ニ",
    romaji: "ni",
    category: "katakana",
    type: "basic",
    column: "n",
  },
  {
    id: 123,
    symbol: "ヌ",
    romaji: "nu",
    category: "katakana",
    type: "basic",
    column: "n",
  },
  {
    id: 124,
    symbol: "ネ",
    romaji: "ne",
    category: "katakana",
    type: "basic",
    column: "n",
  },
  {
    id: 125,
    symbol: "ノ",
    romaji: "no",
    category: "katakana",
    type: "basic",
    column: "n",
  },
  {
    id: 126,
    symbol: "ハ",
    romaji: "ha",
    category: "katakana",
    type: "basic",
    column: "h",
  },
  {
    id: 127,
    symbol: "ヒ",
    romaji: "hi",
    category: "katakana",
    type: "basic",
    column: "h",
  },
  {
    id: 128,
    symbol: "フ",
    romaji: "fu",
    category: "katakana",
    type: "basic",
    column: "h",
  },
  {
    id: 129,
    symbol: "ヘ",
    romaji: "he",
    category: "katakana",
    type: "basic",
    column: "h",
  },
  {
    id: 130,
    symbol: "ホ",
    romaji: "ho",
    category: "katakana",
    type: "basic",
    column: "h",
  },
  {
    id: 131,
    symbol: "マ",
    romaji: "ma",
    category: "katakana",
    type: "basic",
    column: "m",
  },
  {
    id: 132,
    symbol: "ミ",
    romaji: "mi",
    category: "katakana",
    type: "basic",
    column: "m",
  },
  {
    id: 133,
    symbol: "ム",
    romaji: "mu",
    category: "katakana",
    type: "basic",
    column: "m",
  },
  {
    id: 134,
    symbol: "メ",
    romaji: "me",
    category: "katakana",
    type: "basic",
    column: "m",
  },
  {
    id: 135,
    symbol: "モ",
    romaji: "mo",
    category: "katakana",
    type: "basic",
    column: "m",
  },
  {
    id: 136,
    symbol: "ヤ",
    romaji: "ya",
    category: "katakana",
    type: "basic",
    column: "y",
  },
  {
    id: 137,
    symbol: "ユ",
    romaji: "yu",
    category: "katakana",
    type: "basic",
    column: "y",
  },
  {
    id: 138,
    symbol: "ヨ",
    romaji: "yo",
    category: "katakana",
    type: "basic",
    column: "y",
  },
  {
    id: 139,
    symbol: "ラ",
    romaji: "ra",
    category: "katakana",
    type: "basic",
    column: "r",
  },
  {
    id: 140,
    symbol: "リ",
    romaji: "ri",
    category: "katakana",
    type: "basic",
    column: "r",
  },
  {
    id: 141,
    symbol: "ル",
    romaji: "ru",
    category: "katakana",
    type: "basic",
    column: "r",
  },
  {
    id: 142,
    symbol: "レ",
    romaji: "re",
    category: "katakana",
    type: "basic",
    column: "r",
  },
  {
    id: 143,
    symbol: "ロ",
    romaji: "ro",
    category: "katakana",
    type: "basic",
    column: "r",
  },
  {
    id: 144,
    symbol: "ワ",
    romaji: "wa",
    category: "katakana",
    type: "basic",
    column: "w",
  },
  {
    id: 145,
    symbol: "ヲ",
    romaji: "wo",
    category: "katakana",
    type: "basic",
    column: "w",
  },
  {
    id: 146,
    symbol: "ン",
    romaji: "n",
    category: "katakana",
    type: "basic",
    column: "ん",
  },
  // Diacritic Katakana
  {
    id: 147,
    symbol: "ガ",
    romaji: "ga",
    category: "katakana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 148,
    symbol: "ギ",
    romaji: "gi",
    category: "katakana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 149,
    symbol: "グ",
    romaji: "gu",
    category: "katakana",
    type: "diacritic",
    column: "g",
  },
  // Diacritic Katakana
  {
    id: 150,
    symbol: "ゲ",
    romaji: "ge",
    category: "katakana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 151,
    symbol: "ゴ",
    romaji: "go",
    category: "katakana",
    type: "diacritic",
    column: "g",
  },
  {
    id: 152,
    symbol: "ザ",
    romaji: "za",
    category: "katakana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 153,
    symbol: "ジ",
    romaji: "ji",
    category: "katakana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 154,
    symbol: "ズ",
    romaji: "zu",
    category: "katakana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 155,
    symbol: "ゼ",
    romaji: "ze",
    category: "katakana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 156,
    symbol: "ゾ",
    romaji: "zo",
    category: "katakana",
    type: "diacritic",
    column: "z",
  },
  {
    id: 157,
    symbol: "ダ",
    romaji: "da",
    category: "katakana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 158,
    symbol: "ヂ",
    romaji: "ji",
    category: "katakana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 159,
    symbol: "ヅ",
    romaji: "zu",
    category: "katakana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 160,
    symbol: "デ",
    romaji: "de",
    category: "katakana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 161,
    symbol: "ド",
    romaji: "do",
    category: "katakana",
    type: "diacritic",
    column: "d",
  },
  {
    id: 162,
    symbol: "バ",
    romaji: "ba",
    category: "katakana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 163,
    symbol: "ビ",
    romaji: "bi",
    category: "katakana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 164,
    symbol: "ブ",
    romaji: "bu",
    category: "katakana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 165,
    symbol: "ベ",
    romaji: "be",
    category: "katakana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 166,
    symbol: "ボ",
    romaji: "bo",
    category: "katakana",
    type: "diacritic",
    column: "b",
  },
  {
    id: 167,
    symbol: "パ",
    romaji: "pa",
    category: "katakana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 168,
    symbol: "ピ",
    romaji: "pi",
    category: "katakana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 169,
    symbol: "プ",
    romaji: "pu",
    category: "katakana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 170,
    symbol: "ペ",
    romaji: "pe",
    category: "katakana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 171,
    symbol: "ポ",
    romaji: "po",
    category: "katakana",
    type: "diacritic",
    column: "p",
  },
  {
    id: 172,
    symbol: "キャ",
    romaji: "kya",
    category: "katakana",
    type: "combination",
    column: "ky",
  },
  {
    id: 173,
    symbol: "キュ",
    romaji: "kyu",
    category: "katakana",
    type: "combination",
    column: "ky",
  },
  {
    id: 174,
    symbol: "キョ",
    romaji: "kyo",
    category: "katakana",
    type: "combination",
    column: "ky",
  },
  // Combination Katakana
  {
    id: 175,
    symbol: "ギャ",
    romaji: "gya",
    category: "katakana",
    type: "combination",
    column: "gy",
  },
  {
    id: 176,
    symbol: "ギュ",
    romaji: "gyu",
    category: "katakana",
    type: "combination",
    column: "gy",
  },
  {
    id: 177,
    symbol: "ギョ",
    romaji: "gyo",
    category: "katakana",
    type: "combination",
    column: "gy",
  },
  {
    id: 178,
    symbol: "シャ",
    romaji: "sha",
    category: "katakana",
    type: "combination",
    column: "sh",
  },
  {
    id: 179,
    symbol: "シュ",
    romaji: "shu",
    category: "katakana",
    type: "combination",
    column: "sh",
  },
  {
    id: 180,
    symbol: "ショ",
    romaji: "sho",
    category: "katakana",
    type: "combination",
    column: "sh",
  },
  {
    id: 181,
    symbol: "ジャ",
    romaji: "ja",
    category: "katakana",
    type: "combination",
    column: "j",
  },
  {
    id: 182,
    symbol: "ジュ",
    romaji: "ju",
    category: "katakana",
    type: "combination",
    column: "j",
  },
  {
    id: 183,
    symbol: "ジョ",
    romaji: "jo",
    category: "katakana",
    type: "combination",
    column: "j",
  },
  {
    id: 184,
    symbol: "チャ",
    romaji: "cha",
    category: "katakana",
    type: "combination",
    column: "ch",
  },
  {
    id: 185,
    symbol: "チュ",
    romaji: "chu",
    category: "katakana",
    type: "combination",
    column: "ch",
  },
  {
    id: 186,
    symbol: "チョ",
    romaji: "cho",
    category: "katakana",
    type: "combination",
    column: "ch",
  },
  {
    id: 187,
    symbol: "ニャ",
    romaji: "nya",
    category: "katakana",
    type: "combination",
    column: "ny",
  },
  {
    id: 188,
    symbol: "ニュ",
    romaji: "nyu",
    category: "katakana",
    type: "combination",
    column: "ny",
  },
  {
    id: 189,
    symbol: "ニョ",
    romaji: "nyo",
    category: "katakana",
    type: "combination",
    column: "ny",
  },
  {
    id: 190,
    symbol: "ヒャ",
    romaji: "hya",
    category: "katakana",
    type: "combination",
    column: "hy",
  },
  {
    id: 191,
    symbol: "ヒュ",
    romaji: "hyu",
    category: "katakana",
    type: "combination",
    column: "hy",
  },
  {
    id: 192,
    symbol: "ヒョ",
    romaji: "hyo",
    category: "katakana",
    type: "combination",
    column: "hy",
  },
  {
    id: 193,
    symbol: "ビャ",
    romaji: "bya",
    category: "katakana",
    type: "combination",
    column: "by",
  },
  {
    id: 194,
    symbol: "ビュ",
    romaji: "byu",
    category: "katakana",
    type: "combination",
    column: "by",
  },
  {
    id: 195,
    symbol: "ビョ",
    romaji: "byo",
    category: "katakana",
    type: "combination",
    column: "by",
  },
  {
    id: 196,
    symbol: "ピャ",
    romaji: "pya",
    category: "katakana",
    type: "combination",
    column: "py",
  },
  {
    id: 197,
    symbol: "ピュ",
    romaji: "pyu",
    category: "katakana",
    type: "combination",
    column: "py",
  },
  {
    id: 198,
    symbol: "ピョ",
    romaji: "pyo",
    category: "katakana",
    type: "combination",
    column: "py",
  },
  {
    id: 199,
    symbol: "ミャ",
    romaji: "mya",
    category: "katakana",
    type: "combination",
    column: "my",
  },
  {
    id: 200,
    symbol: "ミュ",
    romaji: "myu",
    category: "katakana",
    type: "combination",
    column: "my",
  },
  {
    id: 201,
    symbol: "ミョ",
    romaji: "myo",
    category: "katakana",
    type: "combination",
    column: "my",
  },
  {
    id: 202,
    symbol: "リャ",
    romaji: "rya",
    category: "katakana",
    type: "combination",
    column: "ry",
  },
  {
    id: 203,
    symbol: "リュ",
    romaji: "ryu",
    category: "katakana",
    type: "combination",
    column: "ry",
  },
  {
    id: 204,
    symbol: "リョ",
    romaji: "ryo",
    category: "katakana",
    type: "combination",
    column: "ry",
  },
];
